name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@aave"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_PACKAGES_REGISTRY_READ_ONLY }}
      - name: Aave Fork deployment
        run: npm run deploy:market:aave:fork
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
      - name: Ethereum Fork No Reserves deployment
        run: npm run deploy:market:eth:empty:fork
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
      - name: Test
        run: npm run test
        env:
          ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
